server:
  port: 8080
  tomcat:
    max-http-form-post-size: 50MB

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: photo-bg-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/photo_bg?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: your_mysql_password # 根据实际情况修改
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

# 微信小程序配置
wx:
  miniapp:
    appid: your_wechat_appid
    secret: your_wechat_secret
    rewarded-ad-unit-id: your_ad_unit_id

# Python 图像处理接口配置
python-api:
  base-url: http://127.0.0.1:7860

# MinIO 配置
minio:
  endpoint: https://your-minio-endpoint:9000
  access-key: your_minio_access_key
  secret-key: your_minio_secret_key
  bucket-name: your_bucket_name


# 自定义 NSFW 图片鉴黄校验服务
nsfw:
  enabled: false
  api-url: http://127.0.0.1:3006/checkImg
